### ISSUE TITLE
Database connection attempt times out; migrations do not run

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX_App#110]
On initial deployment, the database connection attempt times out:
```python-traceback
...
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection timed out
	Is the server running on host "aeckart2-postgresql" (10.102.43.194) and accepting
	TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/14/e3q8)
[2021-05-02 16:47:56 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-05-02 16:47:56 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2021-05-02 16:47:56 +0000] [1] [INFO] Using worker: sync
[2021-05-02 16:47:56 +0000] [15] [INFO] Booting worker with pid: 15
[2021-05-02 16:47:57 +0000] [16] [INFO] Booting worker with pid: 16
[2021-05-02 16:47:57 +0000] [18] [INFO] Booting worker with pid: 18
[2021-05-02 16:47:57 +0000] [20] [INFO] Booting worker with pid: 20
[2021-05-02 16:47:57 +0000] [21] [INFO] Booting worker with pid: 21
127.0.0.1 - - [02/May/2021:16:48:10 +0000] "GET / HTTP/1.1" 200 2930 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
```

Eventually, the server gives up and starts listening for requests. The first time it receives a request, it will create the tables. However, because of the connection error, the database migrations are never run.

This can lead to further errors. For example, if the server pod is restarted, it attempts to run the migrations against an unversioned database:
```python-traceback
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> b389abb05262, V1.0-RC.1
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1707, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DuplicateTable: relation "requests" already exists

[SQL: 
CREATE TABLE requests (
	id SERIAL NOT NULL, 
	submit_time TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	did VARCHAR(512) NOT NULL, 
	columns VARCHAR(1024), 
	selection VARCHAR(10485760), 
	tree_name VARCHAR(512), 
	request_id VARCHAR(48) NOT NULL, 
	image VARCHAR(128), 
	chunk_size INTEGER, 
	workers INTEGER, 
	result_destination VARCHAR(32) NOT NULL, 
	result_format VARCHAR(32) NOT NULL, 
	kafka_broker VARCHAR(128), 
	workflow_name VARCHAR(40) NOT NULL, 
	files INTEGER, 
	files_skipped INTEGER, 
	total_events BIGINT, 
	total_bytes BIGINT, 
	did_lookup_time INTEGER, 
	generated_code_cm VARCHAR(128), 
	PRIMARY KEY (id), 
	UNIQUE (request_id)
)

]
(Background on this error at: http://sqlalche.me/e/14/f405)
[2021-05-02 16:21:45 +0000] [1] [INFO] Starting gunicorn 20.1.0
[2021-05-02 16:21:45 +0000] [1] [INFO] Listening at: http://0.0.0.0:5000 (1)
[2021-05-02 16:21:45 +0000] [1] [INFO] Using worker: sync
[2021-05-02 16:21:45 +0000] [15] [INFO] Booting worker with pid: 15
[2021-05-02 16:21:45 +0000] [16] [INFO] Booting worker with pid: 16
[2021-05-02 16:21:45 +0000] [17] [INFO] Booting worker with pid: 17
[2021-05-02 16:21:45 +0000] [18] [INFO] Booting worker with pid: 18
[2021-05-02 16:21:45 +0000] [21] [INFO] Booting worker with pid: 21
```

Thankfully, there is a workaround, which goes as follows:
- Wait (~2 minutes) for the database connection attempt to time out.
- In the meantime, you can open up a terminal inside the PostgreSQL pod:
```
kubectl exec -it <release name>-postgresql-0 -- /bin/bash
Defaulted container "<release name>-postgresql" out of: <release name>-postgresql, init-chmod-data (init)
I have no name!@<release name>-postgresql-0:/$ psql -U postgres servicex
Password for user postgres: 
psql (11.7)
Type "help" for help.

servicex=# 
```
- Make a request (visiting the home page is fine) to trigger table creation. You should see them if you run `\dt;` inside of your `psql` instance.
- If you do not see a table named `alembic_version`, the database is unversioned. You can fix this:
  - Port-forward the database:
  ```
  $ kubectl port-forward <release name>-postgresql-0 5432:5432
  Forwarding from 127.0.0.1:5432 -> 5432
  Forwarding from [::1]:5432 -> 5432
  ```
  - Stamp the version manually from the root directory of this repository:
  ```
  $ FLASK_APP=servicex/app.py APP_CONFIG_FILE=../app.conf flask db stamp head
  INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
  INFO  [alembic.runtime.migration] Will assume transactional DDL.
  INFO  [alembic.runtime.migration] Running stamp_revision  -> 04b9fb8ffee1
  ```
  You should now see an `alembic_version` table in the database.

**Comment by AndrewEckart** [comment]
@BenGalewsky 
I have two theories about why this might happen:
1. After #96 we no longer block waiting for the RabbitMQ connection, so we attempt to migrate before the database pod is ready (i.e. we had a race condition go undiscovered because we were waiting for Rabbit anyway).
2. We were too aggressive in #92 and don't attempt to migrate at all on initial deployment (this seems unlikely though, because it definitely tries to migrate whenever the deployment is restarted).

**Comment by BenGalewsky** [comment]
I'm certain it's the first cause.
I'll take this ticket and use the nifty [NCSA Checks Init Container](https://github.com/ncsa/checks) to pause pod startup til Postgres is up
