### ISSUE TITLE
Docker instructions not working due to missing config values

### ISSUE THREAD

**Issue by AndrewEckart** [ssl-hep/ServiceX_App#93]
# Story
_As a ServiceX developer I want to run the Docker image in a container so I can test it in isolation._

The current documentation for running the app as a Docker image does not seem to work. Steps to reproduce:
- Checkout the develop branch at the latest commit
- Build the Docker image
- Run it using the command in the README

The main culprit seems to be that `docker-dev.conf` is missing a number of required config values.

```
$ docker build . -t servicex_app
...
Successfully built c0028c455e65
Successfully tagged servicex_app:latest
$ docker run --name servicex-app --rm -p8000:5000  --mount type=bind,source="$(pwd)"/sqlite,target=/sqlite  -e APP_CONFIG_FILE=/home/servicex/docker-dev.conf  servicex_app:latest
[2021-04-21 11:24:11 +0000] [18] [INFO] Worker exiting (pid: 18)
[2021-04-21 11:24:11 +0000] [22] [ERROR] Exception in worker process
Traceback (most recent call last):
...
  File "/home/servicex/servicex/__init__.py", line 95, in create_app
    if app.config['OBJECT_STORE_ENABLED']:
KeyError: 'OBJECT_STORE_ENABLED'
[2021-04-21 11:24:11 +0000] [22] [INFO] Worker exiting (pid: 22)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
```

# Acceptance Criteria
1. The Docker image can be run locally by following the documentation.

**Comment by BenGalewsky** [comment]
I'll fix this, however I never use this config any more - I always do a helm install
